
services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:123Sugarcane.@db:5432/postgres?schema=public

  db:
    container_name: db
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123Sugarcane.
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
